title:       "This Is How Me Do It!"
version:     "0010a---14-Feb-2021"
copyright:   "2021-2021"
description: >- 
  Describe1.
  Describe2.
baseurl: "" # e.g. /blog
url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "J. Walker"
address:          "Box 7, Mawitaan, Bangalla."
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://doit.vlsm.org/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/doit"
urlghpage:        "https://doit.vlsm.org/"
keywords:         "jekyll, testing"
github:           [metadata]

